In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import matplotlib.dates as mdates

In [3]:
data = pd.read_excel("./data/practices.xlsx", header=None)

data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,YEAR,SEASON,METHOD OF SOWING,NaN,NaN,NaN,NaN,NaN,APPLICATION OF FERTILIZER,NaN,NaN,NaN,METHOD OF WEEDING,NaN,NaN,NaN
1,NaN,NaN,BROADCASTING,TRANSPLANTING IN ROWS,TRANSPLANTED NOT IN ROWS,PARACHUTE,PLANTING BY MACHINERY,other,CHEMICAL ONLY,ORGANIC ONLY,BOTH,NONE,HAND WEEDING,USING WEEDICIDE,BY USE OF WATER,NO WEEDING
2,1992,Yala,206289,4428,34183,0,0,52,231242,1832,5765,7743,65949,141344,5281,35317
3,1993,Maha,386215,25582,801007,0,0,4407,457118,6535,10623,6378,125113,303198,12065,2955
4,1993,Yala,231523,8556,35255,0,0,327,253777,1034,10739,8809,61162,173641,6267,34184

In [4]:
data.columns = [
    "Year", "Season",
    # Method of Sowing
    "Broadcasting","Transplant_Rows","Transplant_NotRows","Parachute","Machine","Other(sowing)",
    # Application of fertilizer
    "Chemical_only","Organic_only","Both","None",
    # Method of weeding
    "Hand_Weeding","Weedicide","Water","No_Weeding"
    
    
]
data.head()

,Year,Season,Broadcasting,Transplant_Rows,Transplant_NotRows,Parachute,Machine,Other(sowing),Chemical_only,Organic_only,Both,None,Hand_Weeding,Weedicide,Water,No_Weeding
0,YEAR,SEASON,METHOD OF SOWING,NaN,NaN,NaN,NaN,NaN,APPLICATION OF FERTILIZER,NaN,NaN,NaN,METHOD OF WEEDING,NaN,NaN,NaN
1,NaN,NaN,BROADCASTING,TRANSPLANTING IN ROWS,TRANSPLANTED NOT IN ROWS,PARACHUTE,PLANTING BY MACHINERY,other,CHEMICAL ONLY,ORGANIC ONLY,BOTH,NONE,HAND WEEDING,USING WEEDICIDE,BY USE OF WATER,NO WEEDING
2,1992,Yala,206289,4428,34183,0,0,52,231242,1832,5765,7743,65949,141344,5281,35317
3,1993,Maha,386215,25582,801007,0,0,4407,457118,6535,10623,6378,125113,303198,12065,2955
4,1993,Yala,231523,8556,35255,0,0,327,253777,1034,10739,8809,61162,173641,6267,34184

In [5]:
data = data.iloc[2:]
data

,Year,Season,Broadcasting,Transplant_Rows,Transplant_NotRows,Parachute,Machine,Other(sowing),Chemical_only,Organic_only,Both,None,Hand_Weeding,Weedicide,Water,No_Weeding
2,1992,Yala,206289,4428,34183,0,0,52,231242,1832,5765,7743,65949,141344,5281,35317
3,1993,Maha,386215,25582,801007,0,0,4407,457118,6535,10623,6378,125113,303198,12065,2955
4,1993,Yala,231523,8556,35255,0,0,327,253777,1034,10739,8809,61162,173641,6267,34184
5,1994,Maha,425262,17962,90020,0,0,1595,485308,4265,19323,22100,122602,337143,13815,60558
6,1994,Yala,286303,4542,42157,0,0,372,305036,2826,12881,12631,86369,203695,9320,33990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2023,Yala,479837,5101,9809,9148,852,329,308591,5380,189431,1674,47518,437058,4385,16115
65,2024,Maha,760299,5878,14873,24267,1203,154,553363,4234,245506,3570,74576,707115,9481,15501
66,2024,Yala,450440,6249,11477,12464,496,190,313171,18334,147968,1843,51797,413422,5282,10815
67,2025,Maha,762115,7179,11210,19202,380,377,573120,4705,218054,4584,77251,705313,3474,14425
68,2025,Yala,517389,4795,4999,11554,2432,253,400303,1593,137715,1811,40482,486357,7910,6673

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 67 entries, 2 to 68
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                67 non-null     object
 1   Season              67 non-null     str
 2   Broadcasting        67 non-null     object
 3   Transplant_Rows     67 non-null     object
 4   Transplant_NotRows  67 non-null     object
 5   Parachute           67 non-null     object
 6   Machine             67 non-null     object
 7   Other(sowing)       67 non-null     object
 8   Chemical_only       67 non-null     object
 9   Organic_only        67 non-null     object
 10  Both                67 non-null     object
 11  None                67 non-null     object
 12  Hand_Weeding        67 non-null     object
 13  Weedicide           67 non-null     object
 14  Water               67 non-null     object
 15  No_Weeding          67 non-null     object
dtypes: object(15), str(1)
memory usage: 8.5+ KB

In [7]:
data.isnull().sum()

Year                  0
Season                0
Broadcasting          0
Transplant_Rows       0
Transplant_NotRows    0
Parachute             0
Machine               0
Other(sowing)         0
Chemical_only         0
Organic_only          0
Both                  0
None                  0
Hand_Weeding          0
Weedicide             0
Water                 0
No_Weeding            0
dtype: int64

In [8]:
excleude_col = ["Year","Season"]

col_to_convert = data.columns.difference(excleude_col)



data[col_to_convert] = data[col_to_convert].astype(int)

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 67 entries, 2 to 68
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                67 non-null     object
 1   Season              67 non-null     str
 2   Broadcasting        67 non-null     int64
 3   Transplant_Rows     67 non-null     int64
 4   Transplant_NotRows  67 non-null     int64
 5   Parachute           67 non-null     int64
 6   Machine             67 non-null     int64
 7   Other(sowing)       67 non-null     int64
 8   Chemical_only       67 non-null     int64
 9   Organic_only        67 non-null     int64
 10  Both                67 non-null     int64
 11  None                67 non-null     int64
 12  Hand_Weeding        67 non-null     int64
 13  Weedicide           67 non-null     int64
 14  Water               67 non-null     int64
 15  No_Weeding          67 non-null     int64
dtypes: int64(14), object(1), str(1)
memory usage: 8.5+ KB

In [10]:
def create_date(row):
    if row['Season'].lower() == "yala":
        return pd.Timestamp(year = row['Year'], month=4, day=1)
    elif row['Season'].lower() == "maha":
        return pd.Timestamp(year = row['Year']-1, month=9, day=1)
    
data["Date"] = data.apply(create_date,  axis=1)

data = data.sort_values('Date')
data

data = data.set_index("Date")

In [11]:
data.shape

(67, 16)

In [12]:
with pd.ExcelWriter("df_practices.xlsx") as writer:
    data.to_excel(writer, sheet_name="df")